#pragma once
#include "mpi.h"
#include <pthread.h>
#include <stdio.h>
#include <unistd.h>
#include <iostream>
#include <locale>
#include <clocale>
#include <stddef.h>
#include <string>
using std::string;